title: KKKKKKKKKK.love
email: KK@KKKKKKKKKK.love
url: KKKKKKKKKK.love
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)

  
permalink: /:slug.html

favicon: "favicon.png"
#goat_counter: "kkkkkkkkkk" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag